apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-deployment
  labels:
    app: python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: my-python-app:latest
        imagePullPolicy: Never # Important pour Kind si on load l'image manuellement
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          value: "mysql-service" # Nom du service MySQL (à créer ou assumer existant)
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: "password"
        - name: DB_NAME
          value: "test_db"
